version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: vue
      - dependency-name: vuex
      - dependency-name: nuxt
